name: feature_generator
description: A CLI tool to generate Clean Architecture feature structure for Flutter projects
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=2.17.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  path: 
  args:
  flutter_bloc: 
  injectable:
  dartz:
  dio:
dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  
executables:
  feature_generator:

  