name: feature_generator
description: A CLI tool to generate Clean Architecture feature structure for Flutter projects
version: 1.0.0
license: MIT
repository: https://github.com/MOHAMED-ATEF2017/feature_generator.git
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=2.17.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  path: ^1.9.1 
  args: ^2.7.0
  flutter_bloc: ^9.1.0 
  injectable: ^2.5.0
  dartz: ^0.10.1
  dio: ^5.8.0+1
dev_dependencies:
  build_runner: ^2.4.15
  injectable_generator: ^2.7.0
  lints: ^5.0.0
  mockito: ^5.4.6
  test: ^1.25.15
  
executables:
  feature_generator:

  